import type { Metadata } from "next";
import { asc, eq } from "drizzle-orm";
import { db } from "@/db";
import { pages, services } from "@/db/schema";
import { ContactForm } from "@/components/public/contact-form";
import { PageHero } from "@/components/public/sections";
import { buildRouteMetadata, getSiteSettings } from "@/lib/site";
export async function generateMetadata(): Promise<Metadata> { return buildRouteMetadata("/contact", { title: "Contact", description: "Discuss software, AI, IoT, networking, security, cloud or IT support with RedMug IT Solution in Dubai." }); } export const dynamic="force-dynamic";
export default async function ContactPage(){const [[page],settings,serviceRows]=await Promise.all([db.select().from(pages).where(eq(pages.slug,"contact")).limit(1),getSiteSettings(),db.select({id:services.id,name:services.name}).from(services).where(eq(services.status,"PUBLISHED")).orderBy(asc(services.displayOrder))]);const phoneNumbers=settings?[settings.phone,settings.phoneSecondary,settings.phoneMobile].filter((value):value is string=>Boolean(value)):[];return <main id="main-content"><PageHero eyebrow={page?.eyebrow||"Start a conversation"} title={page?.heroTitle||"Bring Us the Problem. We’ll Help Define the System."} description={page?.heroDescription}/><section className="page-body"><div className="site-container contact-layout"><aside className="contact-info"><span className="eyebrow">RedMug / Dubai</span><h2>Tell us what needs to work better.</h2><p>{page?.content}</p>{settings&&<><div className="contact-line"><small>Phone</small>{phoneNumbers.map(number=><a key={number} href={`tel:${number.replace(/[^\d+]/g,"")}`} style={{display:"block"}}>{number}</a>)}</div>{settings.email&&<div className="contact-line"><small>Email</small><a href={`mailto:${settings.email}`}>{settings.email}</a></div>}<div className="contact-line"><small>Address</small><span>{settings.address}</span></div><div className="contact-line"><small>Business hours</small><span>{settings.businessHours}</span></div></>}</aside><ContactForm services={serviceRows}/></div></section></main>}
