import type { Metadata } from "next";
import { and, desc, eq, ne } from "drizzle-orm";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { blogPosts } from "@/db/schema";
import { PageHero, RichText, SectionHead } from "@/components/public/sections";
import { brandTitle } from "@/lib/site";
type Props={params:Promise<{slug:string}>};export const dynamic="force-dynamic";
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const[item]=await db.select().from(blogPosts).where(and(eq(blogPosts.slug,slug),eq(blogPosts.status,"PUBLISHED"))).limit(1);return item?{title:brandTitle(item.seoTitle||item.title),description:item.seoDescription||item.excerpt,alternates:{canonical:`/blog/${item.slug}`},...(item.featuredImage?{openGraph:{type:"article",publishedTime:item.publishedAt?.toISOString(),images:[item.featuredImage]}}:{})}:{}}
export default async function BlogPostPage({params}:Props){const{slug}=await params;const[item]=await db.select().from(blogPosts).where(and(eq(blogPosts.slug,slug),eq(blogPosts.status,"PUBLISHED"))).limit(1);if(!item)notFound();const related=await db.select().from(blogPosts).where(and(eq(blogPosts.status,"PUBLISHED"),ne(blogPosts.id,item.id))).orderBy(desc(blogPosts.publishedAt)).limit(2);const headings=item.content.split("\n").filter(line=>line.startsWith("## ")).map(line=>line.slice(3));const structuredData=[{"@context":"https://schema.org","@type":"Article",headline:item.title,description:item.excerpt,datePublished:item.publishedAt?.toISOString(),dateModified:item.updatedAt.toISOString(),author:{"@type":"Organization",name:"RedMug IT Solution L.L.C."},mainEntityOfPage:`https://redmugitsolution.ae/blog/${item.slug}`},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Insights",item:"https://redmugitsolution.ae/blog"},{"@type":"ListItem",position:2,name:item.title,item:`https://redmugitsolution.ae/blog/${item.slug}`}]}];return <main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><PageHero eyebrow={item.isDemo?"Sample editorial / Insights":"Insights / RedMug"} title={item.title} description={item.excerpt}/><section className="page-body"><div className="site-container content-grid"><article><div className="article-meta"><span>{item.publishedAt?.toLocaleDateString("en-AE",{dateStyle:"long"})}</span><span>{item.readingTime} minute read</span><span>{item.tags.join(" · ")}</span></div>{item.isDemo&&<p className="demo-badge">Sample editorial content</p>}<RichText content={item.content}/><div className="share-row"><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(`https://redmugitsolution.ae/blog/${item.slug}`)}`} target="_blank" rel="noreferrer">Share on LinkedIn</a><a href={`https://x.com/intent/post?url=${encodeURIComponent(`https://redmugitsolution.ae/blog/${item.slug}`)}`} target="_blank" rel="noreferrer">Share on X</a></div></article><aside className="side-panel"><small>In this article</small>{headings.length?headings.map(heading=><span key={heading}>{heading}</span>):<span>Overview</span>}</aside></div></section>{related.length>0&&<section className="section section-dark"><div className="site-container"><SectionHead eyebrow="Continue reading" title="Related insights."/><div className="insights-grid">{related.map(post=><Link className="insight-card" href={`/blog/${post.slug}`} key={post.id}><span className="insight-meta">{post.readingTime} min read</span><h3>{post.title}</h3><p>{post.excerpt}</p></Link>)}</div></div></section>}</main>}
