"use client";
import { useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import Link from "next/link";
import { Bell, BriefcaseBusiness, ChevronRight, FileText, FolderKanban, GalleryHorizontal, Globe2, Images, LayoutDashboard, Menu, MessageSquareText, Newspaper, Search, Settings, ShieldCheck, Sparkles, Users, UserSquare2, X, type LucideIcon } from "lucide-react";
import { BrandMark } from "@/components/brand/logo";
import type { AuthUser } from "@/lib/auth";
type NavItem = [string, string, LucideIcon];
const sections: Array<{ label: string; items: NavItem[] }>=[{label:"",items:[["Dashboard","/admin",LayoutDashboard]]},{label:"Content",items:[["Pages","/admin/pages",FileText],["Services","/admin/services",Sparkles],["Solutions","/admin/solutions",Globe2],["Industries","/admin/industries",FolderKanban],["Projects","/admin/projects",BriefcaseBusiness],["Blog","/admin/blog",Newspaper],["Blog Categories","/admin/blog-categories",FolderKanban],["Careers","/admin/careers",BriefcaseBusiness],["Team","/admin/team",UserSquare2],["Testimonials","/admin/testimonials",MessageSquareText],["Gallery","/admin/gallery",GalleryHorizontal]]},{label:"Business",items:[["Contact Messages","/admin/contacts",MessageSquareText],["Job Applications","/admin/applications",FileText]]},{label:"System",items:[["Media Library","/admin/media",Images],["SEO","/admin/seo",ShieldCheck],["Site Settings","/admin/settings",Settings],["Users","/admin/users",Users]]}];
export function AdminShell({user,newLeads,logoUrl,children}:{user:AuthUser;newLeads:number;logoUrl?:string|null;children:React.ReactNode}){const pathname=usePathname();const router=useRouter();const[open,setOpen]=useState(false);const crumbs=pathname.split("/").filter(Boolean);async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh()}return <div className="admin-app"><aside className={`admin-sidebar ${open?"open":""}`}><div className="admin-brand"><BrandMark href="/admin" compact logoUrl={logoUrl}/></div><nav className="admin-nav" aria-label="Admin navigation">{sections.map(section=><div key={section.label||"main"}>{section.label&&<div className="nav-group">{section.label}</div>}{section.items.map(([label,href,Icon])=>{if((href==="/admin/users"&&user.role!=="SUPER_ADMIN")||(["/admin/settings","/admin/seo","/admin/media","/admin/contacts","/admin/applications"].includes(href)&&user.role==="EDITOR"))return null;const active=href==="/admin"?pathname===href:pathname===href||pathname.startsWith(`${href}/`);return <Link href={href} className={active?"active":""} key={href} onClick={()=>setOpen(false)}><Icon size={15}/>{label}</Link>})}</div>)}</nav><div className="admin-sidebar-foot"><div className="user-mini"><div className="avatar">{user.name.split(" ").map(n=>n[0]).slice(0,2).join("")}</div><div><b>{user.name}</b><small>{user.role.replace("_"," ")}</small></div></div></div></aside>{open&&<button aria-label="Close admin navigation" className="modal-backdrop" style={{border:0}} onClick={()=>setOpen(false)}/>}<div className="admin-main"><header className="admin-topbar"><button className="admin-mobile-toggle" onClick={()=>setOpen(!open)} aria-label="Open admin navigation">{open?<X/>:<Menu/>}</button><div className="admin-search"><Search size={15}/><input placeholder="Search modules and content…" aria-label="Search admin" onKeyDown={e=>{if(e.key==="Enter"){const value=e.currentTarget.value.toLowerCase();const item=sections.flatMap(s=>s.items).find(([label])=>label.toLowerCase().includes(value));if(item)router.push(item[1])}}}/></div><div className="admin-top-actions"><Link href="/admin/contacts" className="icon-button" aria-label={`${newLeads} new notifications`}><Bell size={15}/>{newLeads>0&&<i className="notify-dot"/>}</Link><Link href="/" target="_blank" className="icon-button" aria-label="View website"><Globe2 size={15}/></Link><button className="admin-button" onClick={logout}>Logout</button></div></header><div className="admin-content"><div className="breadcrumbs"><span>RedMug CMS</span>{crumbs.slice(1).map(crumb=><span key={crumb}><ChevronRight size={11}/>{crumb.replaceAll("-"," ")}</span>)}</div>{children}</div></div></div>}
