import type { Metadata } from "next";
import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { careers } from "@/db/schema";
import { ApplicationForm } from "@/components/public/application-form";
import { PageHero } from "@/components/public/sections";
import { brandTitle } from "@/lib/site";
type Props={params:Promise<{slug:string}>};export const dynamic="force-dynamic";
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const[item]=await db.select().from(careers).where(eq(careers.slug,slug)).limit(1);return item?{title:brandTitle(item.seoTitle||item.title),description:item.seoDescription||item.description.slice(0,155),robots:item.status==="OPEN"?undefined:{index:false}}:{}}
export default async function CareerPage({params}:Props){const{slug}=await params;const[item]=await db.select().from(careers).where(and(eq(careers.slug,slug),eq(careers.status,"OPEN"))).limit(1);if(!item)notFound();return <main id="main-content"><PageHero eyebrow={item.isDemo?"Sample opening / Careers":"Careers / RedMug"} title={item.title} description={`${item.department} · ${item.location} · ${item.employmentType}`}/><section className="page-body"><div className="site-container content-grid"><article className="prose">{item.isDemo&&<div className="form-message" style={{border:"1px solid rgba(226,171,61,.35)",color:"#e4bd6b"}}>This is a sample vacancy demonstrating the CMS workflow. It is not an active RedMug vacancy unless an administrator replaces this notice.</div>}<h2>Role overview</h2><p>{item.description}</p><h2>Responsibilities</h2><ul>{item.responsibilities.map(value=><li key={value}>{value}</li>)}</ul><h2>Requirements</h2><ul>{item.requirements.map(value=><li key={value}>{value}</li>)}</ul><h2>Benefits</h2><ul>{item.benefits.map(value=><li key={value}>{value}</li>)}</ul></article><aside className="side-panel"><small>Application</small><span>{item.department}</span><span>{item.location}</span><span>{item.employmentType}</span>{item.experience&&<span>{item.experience}</span>}{item.deadline&&<span>Deadline: {item.deadline}</span>}</aside></div></section><section className="section section-dark"><div className="site-container contact-layout"><div><span className="eyebrow">Apply</span><h2 style={{fontSize:42,letterSpacing:"-.04em"}}>Submit your application.</h2><p style={{color:"#8fa2b7",lineHeight:1.7}}>Applications are validated and stored securely for RedMug administrators to review.</p></div><ApplicationForm careerId={item.id}/></div></section></main>}
